//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace CST.Prdn
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class UtilEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new UtilEntities object using the connection string found in the 'UtilEntities' section of the application configuration file.
        /// </summary>
        public UtilEntities() : base("name=UtilEntities", "UtilEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new UtilEntities object.
        /// </summary>
        public UtilEntities(string connectionString) : base(connectionString, "UtilEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new UtilEntities object.
        /// </summary>
        public UtilEntities(EntityConnection connection) : base(connection, "UtilEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BulkSaleImport> BulkSaleImports
        {
            get
            {
                if ((_BulkSaleImports == null))
                {
                    _BulkSaleImports = base.CreateObjectSet<BulkSaleImport>("BulkSaleImports");
                }
                return _BulkSaleImports;
            }
        }
        private ObjectSet<BulkSaleImport> _BulkSaleImports;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BulkSaleImportInfo> BulkSaleImportInfoes
        {
            get
            {
                if ((_BulkSaleImportInfoes == null))
                {
                    _BulkSaleImportInfoes = base.CreateObjectSet<BulkSaleImportInfo>("BulkSaleImportInfoes");
                }
                return _BulkSaleImportInfoes;
            }
        }
        private ObjectSet<BulkSaleImportInfo> _BulkSaleImportInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BulkSaleResult> BulkSaleResults
        {
            get
            {
                if ((_BulkSaleResults == null))
                {
                    _BulkSaleResults = base.CreateObjectSet<BulkSaleResult>("BulkSaleResults");
                }
                return _BulkSaleResults;
            }
        }
        private ObjectSet<BulkSaleResult> _BulkSaleResults;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PS_TO_NS_PARTNO> PS_TO_NS_PARTNOS
        {
            get
            {
                if ((_PS_TO_NS_PARTNOS == null))
                {
                    _PS_TO_NS_PARTNOS = base.CreateObjectSet<PS_TO_NS_PARTNO>("PS_TO_NS_PARTNOS");
                }
                return _PS_TO_NS_PARTNOS;
            }
        }
        private ObjectSet<PS_TO_NS_PARTNO> _PS_TO_NS_PARTNOS;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BulkSaleImports EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBulkSaleImports(BulkSaleImport bulkSaleImport)
        {
            base.AddObject("BulkSaleImports", bulkSaleImport);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BulkSaleImportInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBulkSaleImportInfoes(BulkSaleImportInfo bulkSaleImportInfo)
        {
            base.AddObject("BulkSaleImportInfoes", bulkSaleImportInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BulkSaleResults EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBulkSaleResults(BulkSaleResult bulkSaleResult)
        {
            base.AddObject("BulkSaleResults", bulkSaleResult);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PS_TO_NS_PARTNOS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPS_TO_NS_PARTNOS(PS_TO_NS_PARTNO pS_TO_NS_PARTNO)
        {
            base.AddObject("PS_TO_NS_PARTNOS", pS_TO_NS_PARTNO);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UtilModel", Name="BulkSaleImport")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BulkSaleImport : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BulkSaleImport object.
        /// </summary>
        /// <param name="runName">Initial value of the RunName property.</param>
        /// <param name="serialNum">Initial value of the SerialNum property.</param>
        public static BulkSaleImport CreateBulkSaleImport(global::System.String runName, global::System.String serialNum)
        {
            BulkSaleImport bulkSaleImport = new BulkSaleImport();
            bulkSaleImport.RunName = runName;
            bulkSaleImport.SerialNum = serialNum;
            return bulkSaleImport;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RunName
        {
            get
            {
                return _RunName;
            }
            set
            {
                if (_RunName != value)
                {
                    OnRunNameChanging(value);
                    ReportPropertyChanging("RunName");
                    _RunName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("RunName");
                    OnRunNameChanged();
                }
            }
        }
        private global::System.String _RunName;
        partial void OnRunNameChanging(global::System.String value);
        partial void OnRunNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustPO
        {
            get
            {
                return _CustPO;
            }
            set
            {
                OnCustPOChanging(value);
                ReportPropertyChanging("CustPO");
                _CustPO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustPO");
                OnCustPOChanged();
            }
        }
        private global::System.String _CustPO;
        partial void OnCustPOChanging(global::System.String value);
        partial void OnCustPOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SerialNum
        {
            get
            {
                return _SerialNum;
            }
            set
            {
                if (_SerialNum != value)
                {
                    OnSerialNumChanging(value);
                    ReportPropertyChanging("SerialNum");
                    _SerialNum = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SerialNum");
                    OnSerialNumChanged();
                }
            }
        }
        private global::System.String _SerialNum;
        partial void OnSerialNumChanging(global::System.String value);
        partial void OnSerialNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LockedStr
        {
            get
            {
                return _LockedStr;
            }
            set
            {
                OnLockedStrChanging(value);
                ReportPropertyChanging("LockedStr");
                _LockedStr = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LockedStr");
                OnLockedStrChanged();
            }
        }
        private global::System.String _LockedStr = "F";
        partial void OnLockedStrChanging(global::System.String value);
        partial void OnLockedStrChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UtilModel", Name="BulkSaleImportInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BulkSaleImportInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BulkSaleImportInfo object.
        /// </summary>
        /// <param name="runName">Initial value of the RunName property.</param>
        /// <param name="serialNum">Initial value of the SerialNum property.</param>
        /// <param name="lockedStr">Initial value of the LockedStr property.</param>
        public static BulkSaleImportInfo CreateBulkSaleImportInfo(global::System.String runName, global::System.String serialNum, global::System.String lockedStr)
        {
            BulkSaleImportInfo bulkSaleImportInfo = new BulkSaleImportInfo();
            bulkSaleImportInfo.RunName = runName;
            bulkSaleImportInfo.SerialNum = serialNum;
            bulkSaleImportInfo.LockedStr = lockedStr;
            return bulkSaleImportInfo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RunName
        {
            get
            {
                return _RunName;
            }
            set
            {
                if (_RunName != value)
                {
                    OnRunNameChanging(value);
                    ReportPropertyChanging("RunName");
                    _RunName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("RunName");
                    OnRunNameChanged();
                }
            }
        }
        private global::System.String _RunName;
        partial void OnRunNameChanging(global::System.String value);
        partial void OnRunNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SerialNum
        {
            get
            {
                return _SerialNum;
            }
            set
            {
                if (_SerialNum != value)
                {
                    OnSerialNumChanging(value);
                    ReportPropertyChanging("SerialNum");
                    _SerialNum = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SerialNum");
                    OnSerialNumChanged();
                }
            }
        }
        private global::System.String _SerialNum;
        partial void OnSerialNumChanging(global::System.String value);
        partial void OnSerialNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustPO
        {
            get
            {
                return _CustPO;
            }
            set
            {
                OnCustPOChanging(value);
                ReportPropertyChanging("CustPO");
                _CustPO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustPO");
                OnCustPOChanged();
            }
        }
        private global::System.String _CustPO;
        partial void OnCustPOChanging(global::System.String value);
        partial void OnCustPOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VendorID
        {
            get
            {
                return _VendorID;
            }
            set
            {
                OnVendorIDChanging(value);
                ReportPropertyChanging("VendorID");
                _VendorID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VendorID");
                OnVendorIDChanged();
            }
        }
        private global::System.String _VendorID;
        partial void OnVendorIDChanging(global::System.String value);
        partial void OnVendorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProdCD
        {
            get
            {
                return _ProdCD;
            }
            set
            {
                OnProdCDChanging(value);
                ReportPropertyChanging("ProdCD");
                _ProdCD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProdCD");
                OnProdCDChanged();
            }
        }
        private global::System.String _ProdCD;
        partial void OnProdCDChanging(global::System.String value);
        partial void OnProdCDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DeptID
        {
            get
            {
                return _DeptID;
            }
            set
            {
                OnDeptIDChanging(value);
                ReportPropertyChanging("DeptID");
                _DeptID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DeptID");
                OnDeptIDChanged();
            }
        }
        private global::System.String _DeptID;
        partial void OnDeptIDChanging(global::System.String value);
        partial void OnDeptIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Cost
        {
            get
            {
                return _Cost;
            }
            set
            {
                OnCostChanging(value);
                ReportPropertyChanging("Cost");
                _Cost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cost");
                OnCostChanged();
            }
        }
        private Nullable<global::System.Decimal> _Cost;
        partial void OnCostChanging(Nullable<global::System.Decimal> value);
        partial void OnCostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LockedStr
        {
            get
            {
                return _LockedStr;
            }
            set
            {
                OnLockedStrChanging(value);
                ReportPropertyChanging("LockedStr");
                _LockedStr = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LockedStr");
                OnLockedStrChanged();
            }
        }
        private global::System.String _LockedStr;
        partial void OnLockedStrChanging(global::System.String value);
        partial void OnLockedStrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProdDescr
        {
            get
            {
                return _ProdDescr;
            }
            set
            {
                OnProdDescrChanging(value);
                ReportPropertyChanging("ProdDescr");
                _ProdDescr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProdDescr");
                OnProdDescrChanged();
            }
        }
        private global::System.String _ProdDescr;
        partial void OnProdDescrChanging(global::System.String value);
        partial void OnProdDescrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HV
        {
            get
            {
                return _HV;
            }
            set
            {
                OnHVChanging(value);
                ReportPropertyChanging("HV");
                _HV = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HV");
                OnHVChanged();
            }
        }
        private global::System.String _HV;
        partial void OnHVChanging(global::System.String value);
        partial void OnHVChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UtilModel", Name="BulkSaleResult")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BulkSaleResult : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BulkSaleResult object.
        /// </summary>
        /// <param name="runName">Initial value of the RunName property.</param>
        /// <param name="serialNum">Initial value of the SerialNum property.</param>
        public static BulkSaleResult CreateBulkSaleResult(global::System.String runName, global::System.String serialNum)
        {
            BulkSaleResult bulkSaleResult = new BulkSaleResult();
            bulkSaleResult.RunName = runName;
            bulkSaleResult.SerialNum = serialNum;
            return bulkSaleResult;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RunName
        {
            get
            {
                return _RunName;
            }
            set
            {
                if (_RunName != value)
                {
                    OnRunNameChanging(value);
                    ReportPropertyChanging("RunName");
                    _RunName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("RunName");
                    OnRunNameChanged();
                }
            }
        }
        private global::System.String _RunName;
        partial void OnRunNameChanging(global::System.String value);
        partial void OnRunNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustPO
        {
            get
            {
                return _CustPO;
            }
            set
            {
                OnCustPOChanging(value);
                ReportPropertyChanging("CustPO");
                _CustPO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustPO");
                OnCustPOChanged();
            }
        }
        private global::System.String _CustPO;
        partial void OnCustPOChanging(global::System.String value);
        partial void OnCustPOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SerialNum
        {
            get
            {
                return _SerialNum;
            }
            set
            {
                if (_SerialNum != value)
                {
                    OnSerialNumChanging(value);
                    ReportPropertyChanging("SerialNum");
                    _SerialNum = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SerialNum");
                    OnSerialNumChanged();
                }
            }
        }
        private global::System.String _SerialNum;
        partial void OnSerialNumChanging(global::System.String value);
        partial void OnSerialNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProdCD
        {
            get
            {
                return _ProdCD;
            }
            set
            {
                OnProdCDChanging(value);
                ReportPropertyChanging("ProdCD");
                _ProdCD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProdCD");
                OnProdCDChanged();
            }
        }
        private global::System.String _ProdCD;
        partial void OnProdCDChanging(global::System.String value);
        partial void OnProdCDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HV
        {
            get
            {
                return _HV;
            }
            set
            {
                OnHVChanging(value);
                ReportPropertyChanging("HV");
                _HV = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HV");
                OnHVChanged();
            }
        }
        private global::System.String _HV;
        partial void OnHVChanging(global::System.String value);
        partial void OnHVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DeptID
        {
            get
            {
                return _DeptID;
            }
            set
            {
                OnDeptIDChanging(value);
                ReportPropertyChanging("DeptID");
                _DeptID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DeptID");
                OnDeptIDChanged();
            }
        }
        private global::System.String _DeptID;
        partial void OnDeptIDChanging(global::System.String value);
        partial void OnDeptIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OrderNo
        {
            get
            {
                return _OrderNo;
            }
            set
            {
                OnOrderNoChanging(value);
                ReportPropertyChanging("OrderNo");
                _OrderNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OrderNo");
                OnOrderNoChanged();
            }
        }
        private global::System.String _OrderNo;
        partial void OnOrderNoChanging(global::System.String value);
        partial void OnOrderNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OrderPO
        {
            get
            {
                return _OrderPO;
            }
            set
            {
                OnOrderPOChanging(value);
                ReportPropertyChanging("OrderPO");
                _OrderPO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OrderPO");
                OnOrderPOChanged();
            }
        }
        private global::System.String _OrderPO;
        partial void OnOrderPOChanging(global::System.String value);
        partial void OnOrderPOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OrderStatus
        {
            get
            {
                return _OrderStatus;
            }
            set
            {
                OnOrderStatusChanging(value);
                ReportPropertyChanging("OrderStatus");
                _OrderStatus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OrderStatus");
                OnOrderStatusChanged();
            }
        }
        private global::System.String _OrderStatus;
        partial void OnOrderStatusChanging(global::System.String value);
        partial void OnOrderStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> OrderDt
        {
            get
            {
                return _OrderDt;
            }
            set
            {
                OnOrderDtChanging(value);
                ReportPropertyChanging("OrderDt");
                _OrderDt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderDt");
                OnOrderDtChanged();
            }
        }
        private Nullable<global::System.DateTime> _OrderDt;
        partial void OnOrderDtChanging(Nullable<global::System.DateTime> value);
        partial void OnOrderDtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExbiStatus
        {
            get
            {
                return _ExbiStatus;
            }
            set
            {
                OnExbiStatusChanging(value);
                ReportPropertyChanging("ExbiStatus");
                _ExbiStatus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExbiStatus");
                OnExbiStatusChanged();
            }
        }
        private global::System.String _ExbiStatus;
        partial void OnExbiStatusChanging(global::System.String value);
        partial void OnExbiStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> OrderLine
        {
            get
            {
                return _OrderLine;
            }
            set
            {
                OnOrderLineChanging(value);
                ReportPropertyChanging("OrderLine");
                _OrderLine = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderLine");
                OnOrderLineChanged();
            }
        }
        private Nullable<global::System.Decimal> _OrderLine;
        partial void OnOrderLineChanging(Nullable<global::System.Decimal> value);
        partial void OnOrderLineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OrderPart
        {
            get
            {
                return _OrderPart;
            }
            set
            {
                OnOrderPartChanging(value);
                ReportPropertyChanging("OrderPart");
                _OrderPart = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OrderPart");
                OnOrderPartChanged();
            }
        }
        private global::System.String _OrderPart;
        partial void OnOrderPartChanging(global::System.String value);
        partial void OnOrderPartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OrderDescr
        {
            get
            {
                return _OrderDescr;
            }
            set
            {
                OnOrderDescrChanging(value);
                ReportPropertyChanging("OrderDescr");
                _OrderDescr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OrderDescr");
                OnOrderDescrChanged();
            }
        }
        private global::System.String _OrderDescr;
        partial void OnOrderDescrChanging(global::System.String value);
        partial void OnOrderDescrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> OrderAmt
        {
            get
            {
                return _OrderAmt;
            }
            set
            {
                OnOrderAmtChanging(value);
                ReportPropertyChanging("OrderAmt");
                _OrderAmt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderAmt");
                OnOrderAmtChanged();
            }
        }
        private Nullable<global::System.Decimal> _OrderAmt;
        partial void OnOrderAmtChanging(Nullable<global::System.Decimal> value);
        partial void OnOrderAmtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Invoice
        {
            get
            {
                return _Invoice;
            }
            set
            {
                OnInvoiceChanging(value);
                ReportPropertyChanging("Invoice");
                _Invoice = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Invoice");
                OnInvoiceChanged();
            }
        }
        private global::System.String _Invoice;
        partial void OnInvoiceChanging(global::System.String value);
        partial void OnInvoiceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> InvoiceLine
        {
            get
            {
                return _InvoiceLine;
            }
            set
            {
                OnInvoiceLineChanging(value);
                ReportPropertyChanging("InvoiceLine");
                _InvoiceLine = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InvoiceLine");
                OnInvoiceLineChanged();
            }
        }
        private Nullable<global::System.Decimal> _InvoiceLine;
        partial void OnInvoiceLineChanging(Nullable<global::System.Decimal> value);
        partial void OnInvoiceLineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> InvoiceAmt
        {
            get
            {
                return _InvoiceAmt;
            }
            set
            {
                OnInvoiceAmtChanging(value);
                ReportPropertyChanging("InvoiceAmt");
                _InvoiceAmt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InvoiceAmt");
                OnInvoiceAmtChanged();
            }
        }
        private Nullable<global::System.Decimal> _InvoiceAmt;
        partial void OnInvoiceAmtChanging(Nullable<global::System.Decimal> value);
        partial void OnInvoiceAmtChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UtilModel", Name="PS_TO_NS_PARTNO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PS_TO_NS_PARTNO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PS_TO_NS_PARTNO object.
        /// </summary>
        /// <param name="iNTERNALID">Initial value of the INTERNALID property.</param>
        /// <param name="nS_NAME">Initial value of the NS_NAME property.</param>
        public static PS_TO_NS_PARTNO CreatePS_TO_NS_PARTNO(global::System.String iNTERNALID, global::System.String nS_NAME)
        {
            PS_TO_NS_PARTNO pS_TO_NS_PARTNO = new PS_TO_NS_PARTNO();
            pS_TO_NS_PARTNO.INTERNALID = iNTERNALID;
            pS_TO_NS_PARTNO.NS_NAME = nS_NAME;
            return pS_TO_NS_PARTNO;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String INTERNALID
        {
            get
            {
                return _INTERNALID;
            }
            set
            {
                if (_INTERNALID != value)
                {
                    OnINTERNALIDChanging(value);
                    ReportPropertyChanging("INTERNALID");
                    _INTERNALID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("INTERNALID");
                    OnINTERNALIDChanged();
                }
            }
        }
        private global::System.String _INTERNALID;
        partial void OnINTERNALIDChanging(global::System.String value);
        partial void OnINTERNALIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NS_NAME
        {
            get
            {
                return _NS_NAME;
            }
            set
            {
                if (_NS_NAME != value)
                {
                    OnNS_NAMEChanging(value);
                    ReportPropertyChanging("NS_NAME");
                    _NS_NAME = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("NS_NAME");
                    OnNS_NAMEChanged();
                }
            }
        }
        private global::System.String _NS_NAME;
        partial void OnNS_NAMEChanging(global::System.String value);
        partial void OnNS_NAMEChanged();

        #endregion
    
    }

    #endregion
    
}
